# Generated by Django 5.2.12 on 2026-04-25 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MoodEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(auto_now_add=True)),
                (
                    "mood_level",
                    models.IntegerField(
                        choices=[
                            (1, "😫 Жахливо"),
                            (2, "😔 Погано"),
                            (3, "😐 Нормально"),
                            (4, "😊 Добре"),
                            (5, "🤩 Чудово"),
                        ]
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("had_panic_attack", models.BooleanField(default=False)),
            ],
        ),
    ]
