# Generated by Django 6.0.4 on 2026-05-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('mood_level', models.IntegerField(choices=[(1, '😫 Жахливо'), (2, '😔 Погано'), (3, '😐 Нормально'), (4, '😊 Добре'), (5, '🤩 Чудово')])),
                ('note', models.TextField(blank=True, null=True)),
                ('had_panic_attack', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
