# Generated by Django 5.2.12 on 2026-05-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_page", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="moodentry",
            name="sleep_quality",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
