# Generated by Django 5.2.12 on 2026-05-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user_page", "0002_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="reminders_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
