# Generated by Django 6.0.4 on 2026-05-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='banned_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Забанений до'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Преміум діє до'),
        ),
    ]
