# Generated by Django 6.0.3 on 2026-04-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст')),
                ('category', models.CharField(choices=[('advice', 'Порада'), ('exercise', 'Вправа')], default='advice', max_length=10, verbose_name='Категорія')),
                ('card_color', models.CharField(default='#FCE4EC', max_length=7, verbose_name='Колір картки (HEX)')),
            ],
        ),
    ]
