# Generated by Django 6.0.3 on 2026-04-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='В обраному'),
        ),
    ]
